Project/BTL/MobileStore/MobileStore/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MobileStore.Models.DAO;
using MobileStore.Models.Entity;

namespace MobileStore.Controllers
{
    public class AjaxController : Controller
    {
        // GET: Ajax
        QL_Hang db = new QL_Hang();
        public ActionResult LoadAllProduct()
        {
            return View();
        }

        public ActionResult LoadTypeProduct()
        {
            CategoryDAO categoryDAO = new CategoryDAO();
            return PartialView(categoryDAO.SelectAll());
        }

        public ActionResult LoadProductByTypeID(int id, int page = 1, int pageSize = 20)
        {
            var product = new ProductDAO().GetByTypeId(id);
            ViewBag.Product = product;
            int totalRecord = 10;
            var model = new ProductDAO().ListByTypeId(id, ref totalRecord, page, pageSize);
            ViewBag.Id = id;
            ViewBag.Total = totalRecord;
            ViewBag.Page = page;

            int maxPage = 10;
            int totalPage = 0;

            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = maxPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;

            return View(model);
        }

        public ActionResult GetProductByTypeId(int id)
        {
            ProductDAO productDAO = new ProductDAO();
            return View(productDAO.GetByTypeId(id));
        }
       
        /*[HttpPost]
        public ActionResult SearchProduct(FormCollection f)
        {
            String keyword = f["txtTimKiem"].ToString();
            List<Product> ListProducts = db.Products.Where(n => n.productName.Contains(keyword)).ToList();
            if(ListProducts.Count == 0)
            {
                ViewBag.notification = "không tìm thấy sản phẩm";              
            }
            return View(db.Products.OrderBy(n => n.productName).ToList());
        }*/
        public ActionResult SearchProduct(String Search)
        {
            return View(db.Products.Where(n => n.productName.StartsWith(Search)));
        }

    }
}

Project/BTL/MobileStore/MobileStore/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MobileStore.Models.Entity;
using PagedList;
using MobileStore.Models.DAO;

namespace MobileStore.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Products(int? page)
        {
            QL_Hang db = new QL_Hang();
            // 1. Tham số int? dùng để thể hiện null và kiểu int
            // page có thể có giá trị là null và kiểu int.

            // 2. Nếu page = null thì đặt lại là 1.
            if (page == null) page = 1;

            // 3. Tạo truy vấn, lưu ý phải sắp xếp theo trường nào đó, ví dụ OrderBy
            // theo LinkID mới có thể phân trang.
            var links = (from l in db.Products
                         select l).OrderBy(x => x.productID);

            // 4. Tạo kích thước trang (pageSize) hay là số Link hiển thị trên 1 trang
            int pageSize = 3;

            // 4.1 Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            int pageNumber = (page ?? 1);

            // 5. Trả về các Link được phân trang theo kích thước và số trang.
            return View(links.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult GetAllProduct()
        {
            ProductDAO productDAO = new ProductDAO();
            ViewBag.products = productDAO.SelectAll();
            return View();
        }

        public ActionResult LoadAllProduct()
        {
            ProductDAO productDAO = new ProductDAO();
            return View(productDAO.SelectAll());
        }

        public ActionResult GetProductDetails(int id)
        {
            ProductDAO productDAO = new ProductDAO();
            return PartialView(productDAO.GetByTypeId(id));
        }

        public ActionResult ProductDetail(int id)
        {
            QL_Hang db = new QL_Hang();
            List<Product> products = db.Products.ToList();
            List<Image> images = db.Images.ToList();

            var result = from p in products
                         join i in images on p.productID equals i.productID
                         where p.productID == id
                         select new productViewModel { product = p, image = i };

            return View(result);
        }

        [ChildActionOnly]
        public ActionResult ProductInfor(int id)
        {
            ProductDAO productDAO = new ProductDAO();
            return PartialView("_ProductInfor", productDAO.GetById(id));
        }

        [ChildActionOnly]
        public ActionResult ProductByID(int id)
        {
            ProductDAO productDAO = new ProductDAO();
            return PartialView("_ProductByID", productDAO.GetById(id));
        }

       
        [ChildActionOnly]
        public ActionResult ProductIntro(int id)
        {
            ProductDAO productDAO = new ProductDAO();
            return PartialView("_ProductIntro", productDAO.GetById(id));
        }

        [ChildActionOnly]
        public ActionResult GetProductById(int id)
        {
            ProductDAO productDAO = new ProductDAO();
            return PartialView("_GetProductByID",productDAO.GetById(id));
        }
    }
}

Project/BTL/MobileStore/MobileStore/Views/Shared/_CheckoutLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Smart Cellular</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Admin/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="~/Content/Admin/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="~/Content/Admin/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="~/Content/Admin/vendors/iCheck/skins/flat/green.css" rel="stylesheet">

    <link href="~/Content/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/fontawesome.css" rel="stylesheet" />
    <link href="~/Content/css/owl.css" rel="stylesheet" />
    <link href="~/Content/css/style.css" rel="stylesheet" />
    

    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <!-- Title  -->
    <!-- Core Style CSS -->
    <link href="~/Content/Cart/css/core-style.css" rel="stylesheet" />

    <!-- Responsive CSS -->

    <link href="~/Content/Cart/css/responsive.css" rel="stylesheet" />
    <script src="~/Content/jquery/jquery.min.js"></script>

</head>
<body style="height: 500px;">
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->
    <!-- Header -->
    <!-- Header -->
    <div class="sub-header">
        <div class="container checkout">
            <div class="row">
                <div class="col-md-8 col-xs-12">
                    <ul class="left-info">
                        <li><a href="https://mail.google.com/"><i class="fa fa-envelope"></i>smartcellular@company.com</a></li>
                        <li><a href="#"><i class="fa fa-phone"></i>0967.666.888</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="right-icons">
                        <li><a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="https://twitter.com/"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="https://www.linkedin.com/"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="Header" style="background: #343434; height:80px;">
        <div class="container checkout">
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-expand-lg">
                        <div class="container">
                            <a class="navbar-brand" href='@Url.Action(" Index", "Home")'><h2>Smart Cellular<em> Website</em></h2></a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="navbarResponsive">
                                <ul class="navbar-nav ml-auto" style="line-height: 70px;">
                                    <li class="nav-item">
                                        <a class="nav-link" href='@Url.Action("Index", "Home")'>
                                            Home
                                            <span class="sr-only">(current)</span>
                                        </a>
                                    </li>
                                    @Html.Action("LoadTypeProduct", "Ajax")
                                    <li class="nav-item">
                                        <a class="nav-link" href='@Url.Action("Checkout", "Checkout")'>Checkout</a>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">About</a>

                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" href='@Url.Action("About", "About")'>About Us</a>
                                            <a class="dropdown-item" href='@Url.Action("Blog", "Blog")'>Blog</a>
                                            <a class="dropdown-item" href='@Url.Action("Testimonials", "Testimonials")'>Testimonials</a>
                                            <a class="dropdown-item" href='@Url.Action("Terms", "Terms")'>Terms</a>
                                        </div>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href='@Url.Action("Contact", "Contact")'>Contact Us</a>
                                    </li>
                                    <li class="nav-item">
                                        @{Html.RenderAction("GetNumber", "Cart");}
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>

    </div>

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="main-banner header-text" id="top" style="min-height: 450px;">
        @RenderBody();
    </div>
    <!-- Banner Ends Here -->

    <div class="sub-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p>
                        Design by: Smart Cellular
                    </p>
                </div>
            </div>
        </div>
    </div>

    <!-- ****** Cart Area End ****** -->
    <!-- /.wrapper end -->
    <!-- jQuery (Necessary for All JavaScript Plugins) -->
    <script src="~/Content/Cart/js/jquery/jquery-1.8.3.min.js"></script>
    <script src="js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="js/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="js/bootstrap.min.js"></script>
    <!-- Plugins js -->
    <script src="js/plugins.js"></script>
    <!-- Active js -->
    <script src="js/active.js"></script>

    <!-- Bootstrap core JavaScript -->
    <script src="~/Content/jquery/jquery.min.js"></script>
    <script src="~/Content/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Additional Scripts -->
    <script src="~/Content/js/custom.js"></script>
    <script src="~/Content/js/owl.js"></script>
    <script src="~/Content/js/slick.js"></script>
    <script src="~/Content/js/accordions.js"></script>

    <script language="text/Javascript">
        cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
        function clearField(t) {                   //declaring the array outside of the
            if (!cleared[t.id]) {                      // function makes it static and global
                cleared[t.id] = 1;  // you could use true and false, but that's more typing
                t.value = '';         // with more chance of typos
                t.style.color = '#fff';
            }
        }
    </script>
    <script type="text/javascript">
        $("li").click(function (e) {
            var catid = $(this).attr("id");


            $.ajax({
                url: '/ Product/LoadAllProduct',
                data: { "id": catid },
                success: function (response) {
                    $('#result').html(response);
                }
            });
        });

    </script>




    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("updateCarts", required: false)
</body>
</html>

Project/BTL/MobileStore/MobileStore/Views/Shared/_HomeLayout.cshtml
@{ 
    var listPro = (List<MobileStore.Models.Entity.Product>)ViewBag.listPro;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home - Smart Cellular</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Admin/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="~/Content/Admin/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="~/Content/Admin/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="~/Content/Admin/vendors/iCheck/skins/flat/green.css" rel="stylesheet">

    <link href="~/Content/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/fontawesome.css" rel="stylesheet" />
    <link href="~/Content/css/owl.css" rel="stylesheet" />
    <link href="~/Content/css/style.css" rel="stylesheet" />

</head>
<body>
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->
    <!-- Header -->
    <!-- Header -->
    <div class="sub-header">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <ul class="left-info row">
                        <li class="col-lg-6"><a href="https://mail.google.com/"><i class="fa fa-envelope"></i>abc@gmail.com</a></li>
                        <li class="col-lg-6"><a href="#"><i class="fa fa-phone"></i>0967.666.888</a></li>
                    </ul>
                </div>
                <div class="col-md-4" style="float: right">
                    <ul>
                        <li>
                            @using (Html.BeginForm("SearchProduct", "Ajax"))
                            {
                                @Html.TextBox("Search", "", htmlAttributes: new { @class = "TextBoxSearch", @placeholder = "Tìm Kiếm" });
                                <input type="submit" value="Search" />
                            }
                        </li>
                    </ul>
                </div>
                <div class="col-md-4" id="txtTimKiem">
                    <ul class="right-icons">
                        <li><a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="https://twitter.com/"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="https://www.linkedin.com/"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="@Url.Action("Logout", "AdminPage")"> Logout</a></li>
                    </ul>

                </div>
            </div>

        </div>
    </div>

    <header class="">
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" href='@Url.Action(" Index", "Home")'><h2>Smart Cellular<em> Website</em></h2></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto" style="line-height: 70px;">
                        <li class="nav-item">
                            <a class="nav-link" href='@Url.Action("Index", "Home")'>
                                Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        @Html.Action("LoadTypeProduct", "Ajax")
                        <li class="nav-item">
                            <a class="nav-link" href='@Url.Action("Checkout", "Checkout")'>Checkout</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">About</a>

                            <div class="dropdown-menu">
                                <a class="dropdown-item" href='@Url.Action("About", "About")'>About Us</a>
                                <a class="dropdown-item" href='@Url.Action("Blog", "Blog")'>Blog</a>
                                <a class="dropdown-item" href='@Url.Action("Testimonials", "Testimonials")'>Testimonials</a>
                                <a class="dropdown-item" href='@Url.Action("Terms", "Terms")'>Terms</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href='@Url.Action("Contact", "Contact")'>Contact Us</a>
                        </li>
                        <li class="nav-item">
                            @Html.Action("GetNumber", "Cart")
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="main-banner header-text" id="top">
        <div class="Modern-Slider">
            <!-- Item -->
            <div class="item item-1">
                <div class="img-fill">
                    <div class="text-content">
                        <h6>Smart Cellular cửa hàng điện thoại uy tín hàng đầu Việt Nam</h6>
                        <h4>Sản phẩm chính hãng, mẫu mã đa dạng,<br /> bảo hành trọn đời</h4>
                        <p>Với những sản phẩm chất lượng chính hãng, bạn sẽ được hưởng rất nhiều ưu đãi và hỗ trợ khi mua tại Smart Cellular, bạn còn chờ gì nữa mà không sắm ngay một chiếc điện thoại chính hãng tại Smart Cellular.</p>
                        <a href='@Url.Action("Products", "Product")' class="filled-button">Products</a>
                    </div>
                </div>
            </div>
            <!-- // Item -->
            <!-- Item -->
            <div class="item item-2">
                <div class="img-fill">
                    <div class="text-content">
                        <h6>Smart Cellular - cửa hàng bán điện thoại lớn nhất cả nước</h6>
                        <h4>Bạn đang muốn mua điện thoại?</h4>
                        <p>Là một trong những cửa hàng uy tín trên toàn quốc, chúng tôi cam kết với khách hàng những sản phẩm chính hãng, chất lượng, giá cả hợp lý.</p>
                        <a href='@Url.Action("About", "About")' class="filled-button">About Us</a>
                    </div>
                </div>
            </div>
            <!-- // Item -->
            <!-- Item -->
            <div class="item item-3">
                <div class="img-fill">
                    <div class="text-content">
                        <h6>Smart Cellular cửa hàng điện thoại uy tín hàng đầu Việt Nam</h6>
                        <h4>Sản phẩm chính hãng, mẫu mã đa dạng,<br /> bảo hành trọn đời</h4>
                        <p>Với những sản phẩm chất lượng chính hãng, bạn sẽ được hưởng rất nhiều ưu đãi và hỗ trợ khi mua tại Smart Cellular, bạn còn chờ gì nữa mà không sắm ngay một chiếc điện thoại chính hãng tại Smart Cellular.</p>
                        <a href='@Url.Action("Contact", "Contact")' class="filled-button">Contact Us</a>
                    </div>
                </div>
            </div>
            <!-- // Item -->
        </div>
    </div>
    <!-- Banner Ends Here -->
    @RenderBody();
    <div class="sub-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p>
                        Design by: Smart Cellular
                    </p>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="~/Content/jquery/jquery.min.js"></script>
    <script src="~/Content/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Additional Scripts -->
    <script src="~/Content/js/custom.js"></script>
    <script src="~/Content/js/owl.js"></script>
    <script src="~/Content/js/slick.js"></script>
    <script src="~/Content/js/accordions.js"></script>

    <script language="text/Javascript">
        cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
        function clearField(t) {                   //declaring the array outside of the
            if (!cleared[t.id]) {                      // function makes it static and global
                cleared[t.id] = 1;  // you could use true and false, but that's more typing
                t.value = '';         // with more chance of typos
                t.style.color = '#fff';
            }
        }
    </script>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Project/BTL/MobileStore/MobileStore/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Smart Cellular</title>

    <!-- Bootstrap -->
    <link href="~/Content/Admin/build/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link href="~/Content/Admin/build/css/font-awesome.min.css" rel="stylesheet" />
    <!-- NProgress -->
    <link href="~/Content/Admin/build/css/nprogress.css" rel="stylesheet" />
    <!-- Animate.css -->
    <link href="~/Content/Admin/build/css/animate.min.css" rel="stylesheet" />

    <!-- Custom Theme Style -->
    <link href="~/Content/Admin/build/css/custom.min.css" rel="stylesheet" />

</head>
@RenderBody();
</html>

Project/BTL/MobileStore/MobileStore/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Smart Cellular</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Admin/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="~/Content/Admin/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="~/Content/Admin/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="~/Content/Admin/vendors/iCheck/skins/flat/green.css" rel="stylesheet">

    <link href="~/Content/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/fontawesome.css" rel="stylesheet" />
    <link href="~/Content/css/owl.css" rel="stylesheet" />
    <link href="~/Content/css/style.css" rel="stylesheet" />
</head>
<body>
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->
    <!-- Header -->
    <!-- Header -->
    <div class="sub-header">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <ul class="left-info row">
                        <li class="col-lg-6"><a href="https://mail.google.com/"><i class="fa fa-envelope"></i>abc@gmail.com</a></li>
                        <li class="col-lg-6"><a href="#"><i class="fa fa-phone"></i>0967.666.888</a></li>
                    </ul>
                </div>
                <div class="col-md-4" style="float: right">
                    <ul>
                        <li>
                                @using (Html.BeginForm("SearchProduct", "Ajax"))
                                {
                                    @Html.TextBox("Search", "", htmlAttributes: new { @class = "TextBoxSearch", @placeholder = "Tìm Kiếm" });
                                    <input type="submit" value="Search" />
                                }
                        </li>
                    </ul>
                </div>
                <div class="col-md-4" id="txtTimKiem">
                    <ul class="right-icons">
                        <li><a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="https://twitter.com/"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="https://www.linkedin.com/"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="@Url.Action("Logout", "AdminPage")"> Logout</a></li>
                    </ul>
                    
                </div>
            </div>

        </div>

    </div>
    
    <header class="">
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" href='@Url.Action(" Index", "Home")'><h2>Smart Cellular</h2></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto" style="line-height: 70px;">
                        <li class="nav-item">
                            <a class="nav-link" href='@Url.Action("Index", "Home")'>
                                Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        @Html.Action("LoadTypeProduct", "Ajax")
                        <li class="nav-item">
                            <a class="nav-link" href='@Url.Action("Checkout", "Checkout")'>Checkout</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">About</a>

                            <div class="dropdown-menu">
                                <a class="dropdown-item" href='@Url.Action("About", "About")'>About Us</a>
                                <a class="dropdown-item" href='@Url.Action("Blog", "Blog")'>Blog</a>
                                <a class="dropdown-item" href='@Url.Action("Testimonials", "Testimonials")'>Testimonials</a>
                                <a class="dropdown-item" href='@Url.Action("Terms", "Terms")'>Terms</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href='@Url.Action("Contact", "Contact")'>Contact Us</a>
                        </li>
                        <li class="nav-item">
                            @{Html.RenderAction("GetNumber", "Cart");}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="main-banner header-text" id="top">
        @RenderBody();
    </div>
    <!-- Banner Ends Here -->



    <div class="sub-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p>
                        Design by: Smart Cellular
                    </p>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="~/Content/jquery/jquery.min.js"></script>
    <script src="~/Content/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Additional Scripts -->
    <script src="~/Content/js/custom.js"></script>
    <script src="~/Content/js/owl.js"></script>
    <script src="~/Content/js/slick.js"></script>
    <script src="~/Content/js/accordions.js"></script>

    <script language="text/Javascript">
        cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
        function clearField(t) {                   //declaring the array outside of the
            if (!cleared[t.id]) {                      // function makes it static and global
                cleared[t.id] = 1;  // you could use true and false, but that's more typing
                t.value = '';         // with more chance of typos
                t.style.color = '#fff';
            }
        }
    </script>
    <script type="text/javascript">
        $("li").click(function (e) {
            var catid = $(this).attr("id");


            $.ajax({
                url: '/ Product/LoadAllProduct',
                data: { "id": catid },
                success: function (response) {
                    $('#result').html(response);
                }
            });
        });

    </script>




    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("updateCarts", required: false)
</body>
</html>